name: renthub-api build CI

on:
  push:
    tags:
      - "v*"

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: mysql:9.0.1
        ports:
          - 3306:3306
        env:
          DB_PORT: 3306
          DB_HOST: spherus-mysql-db
          MYSQL_DATABASE: spherus-db
          MYSQL_USER: Lukasz
          MYSQL_PASSWORD: Pomidor@85
          MYSQL_ROOT_PASSWORD: Pomidor@85
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Run tests
        run: npm i && npm run test

  dockerProd:
    needs: test
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          target: prod
          platforms: linux/amd64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }}:latest
            ${{ steps.meta.outputs.tags }}